name: Maven Java 14

on: workflow_dispatch

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Maven info
      run: |
        ls
        mvn --help
        mvn --version
    
    #- name: Build project with Maven
    #  run: mvn -B package --file pom.xml
    # no pom yet
